(* Created by Wolfram Mathematica 9.0 : www.wolfram.com *)
{"ing", "ter", "ble", "con", "cal", "est", "dis", "per", "ver", "ous", "com", 
 "man", "tor", "der", "ful", "pro", "pre", "non", "bly", "tic", "tal", "mis", 
 "ish", "bil", "ist", "ism", "ate", "lat", "par", "ten", "cat", "ies", "out", 
 "tri", "lar", "men", "sub", "son", "ton", "mer", "car", "ber", "mon", "gen", 
 "for", "ize", "ger", "nal", "col", "can", "tra", "mat", "cor", "den", "nat", 
 "pen", "ven", "fer", "sis", "lec", "tar", "age", "tur", "lin", "cen", "tro", 
 "log", "bar", "ent", "pos", "mar", "ant", "sen", "tle", "rat", "pol", "mal", 
 "tan", "met", "pli", "mor", "ted", "tin", "ner", "the", "let", "min", "ics", 
 "dle", "pho", "sur", "val", "ser", "des", "nar", "cap", "cer", "por", "way", 
 "mas", "wom", "pal", "tat", "net", "tel", "ple", "pan", "cur", "cle", "rec", 
 "ler", "low", "ral", "tem", "pet", "gan", "cre", "duc", "gar", "mit", "sal", 
 "mil", "tis", "bal", "gle", "chi", "ley", "ces", "cus", "mod", "cel", "sem", 
 "vis", "lit", "mag", "cir", "res", "har", "fin", "mul", "phy", "qui", "gat", 
 "fac", "try", "gal", "bat", "mus", "her", "cul", "pas", "cho", "sol", "sin", 
 "mar", "set", "pri", "nom", "cep", "bel", "tes", "van", "sup", "syn", "del", 
 "sti", "cum", "bur", "cil", "mid", "dic", "ban", "pat", "bus", "ern", "pur", 
 "dom", "cas", "til", "leg", "ric", "sor", "bra", "sec", "ris", "lan", "gra", 
 "sat", "san", "tus", "lus", "dal", "ron", "pin", "pot", "var", "sim", "tol", 
 "dro", "sta", "air", "fil", "lis", "don", "car", "cut", "ran", "tom", "dem", 
 "ion", "bon", "sid", "mel", "lay", "fec", "dor", "ret", "sun", "dec", "bit", 
 "sus", "lim", "ren", "rel", "vid", "win", "but", "tiv", "rep", "pop", "lic", 
 "sum", "row", "cro", "lon", "vat", "cid", "dat", "ard", "sea", "bri", "war", 
 "vin", "thy", "bas", "fan", "liv", "pit", "rus", "pel", "nel", "jec", "reg", 
 "sym", "bod", "las", "ham", "psy", "cit", "mak", "cha", "cov", "cop", "put", 
 "dog", "ers", "top", "fal", "kin", "cli", "pon", "fur", "cam", "sil", "sex", 
 "lum", "len", "dan", "wor", "flu", "rid", "bed", "neu", "day", "fit", "ges", 
 "gas", "nes", "les", "pul", "hon", "vel", "sky", "med", "cos", "gun", "ney", 
 "hen", "sep", "mic", "tum", "far", "sar", "bor", "nor", "mes", "sul", "ped", 
 "ves", "get", "pha", "hor", "eth", "lib", "rev", "law", "lam", "fly", "bag", 
 "ram", "phe", "vil", "dra", "lac", "tee", "bet", "dig", "dif", "fes", "lab", 
 "nol", "bar", "box", "ker", "nas", "ply", "nus", "mem", "nam", "cru", "mon", 
 "pow", "sel", "cra", "bol", "bid", "con", "pil", "ber", "nut", "ded", "ket", 
 "tho", "pla", "tim", "hal", "che", "aer", "pus", "ied", "som", "ite", "sig", 
 "ses", "fat", "cot", "sia", "gam", "lem", "hol", "nos", "tiz", "pay", "suf", 
 "her", "syl", "lev", "god", "off", "boy", "tax", "mac", "ums", "din", "thi", 
 "fla", "ess", "spe", "fun", "wit", "key", "fen", "viv", "clu", "not", "run", 
 "bin", "lig", "lie", "cin", "tam", "gel", "bro", "pac", "lot", "act", "vol", 
 "tab", "dol", "lop", "rot", "eye", "han", "gin", "rie", "tec", "ras", "dam", 
 "phi", "num", "tru", "gon", "mad", "cou", "vor", "mol", "fus", "cog", "cod", 
 "cis", "cau", "bow", "rac", "fle", "rin", "pis", "rap", "his", "mur", "liz", 
 "gor", "ken", "nis", "bot", "wil", "pub", "red", "vir", "cow", "fed", "pic", 
 "dil", "nan", "nie", "hem", "niz", "gre", "fix", "rig", "suc", "vig", "cip", 
 "hot", "hap", "vac", "vul", "fig", "los", "saw", "bob", "ure", "tip", "nic", 
 "tag", "lid", "gus", "gli", "ice", "dul", "tac", "hos", "ear", "cor", "rad", 
 "pec", "tak", "sit", "dev", "tox", "bun", "par", "har", "git", "see", "pig", 
 "doc", "gly", "nec", "rol", "sey", "cal", "pid", "rag", "sie", "tun", "tre", 
 "arm", "rum", "tie", "pes", "big", "rav", "dus", "end", "dip", "fab", "cab", 
 "vet", "ine", "ben", "bug", "wag", "zle", "lor", "dit", "say", "sto", "spi", 
 "sha", "gla", "siz", "qua", "dar", "ced", "cad", "per", "man", "liq", "pep", 
 "cav", "nip", "did", "wan", "sad", "tif", "fas", "bac", "hab", "tha", "dri", 
 "sac", "hom", "hum", "dow", "nit", "tow", "def", "pun", "rar", "fet", "tia", 
 "sev", "pir", "nin", "got", "typ", "glo", "ged", "mir", "cia", "tit", "stu", 
 "pro", "mal", "ref", "joy", "lip", "neg", "mot", "mog", "vic", "sci", "fra", 
 "fis", "wal", "civ", "bul", "ick", "sau", "wig", "tid", "ben", "boo", "ian", 
 "art", "gos", "lyt", "ril", "vit", "nau", "bre", "sap", "mau", "mud", "ken", 
 "hip", "hat", "gov", "nog", "tet", "seg", "dep", "mys", "nif", "ive", "cob", 
 "clo", "rup", "tas", "tog", "nav", "cif", "lap", "det", "wil", "aus", "riv", 
 "max", "eat", "nun", "nap", "mos", "sic", "lep", "new", "diz", "glu", "bic", 
 "lad", "riz", "ste", "jur", "wea", "rab", "mor", "mil", "nee", "jus", "mov", 
 "hog", "gal", "fox", "fic", "fea", "dry", "dar", "n't", "rod", "rob", "col", 
 "mum", "cam", "gia", "gum", "fog", "zen", "sug", "sam", "gee", "tir", "oid", 
 "fre", "bad", "rea", "mer", "mel", "meg", "lym", "hyp", "hel", "ham", "giv", 
 "hib", "pee", "flo", "fem", "dot", "plo", "vey", "gru", "mut", "gut", "cas", 
 "can", "jol", "bur", "lux", "bel", "ior", "dim", "fel", "hop", "ros", "aus", 
 "shi", "miz", "dex", "zon", "que", "bee", "gro", "nym", "lut", "wal", "tea", 
 "san", "sal", "plu", "nor", "mac", "sav", "lax", "kil", "jig", "pru", "hur", 
 "hob", "hes", "gar", "sip", "ror", "emp", "sys", "eas", "dun", "dox", "dew", 
 "sir", "del", "tex", "tut", "fee", "rog", "chi", "use", "cup", "bou", "hoo", 
 "zer", "tot", "roy", "rhe", "how", "bis", "gri", "loy", "ien", "rip", "fir", 
 "gis", "die", "gua", "sas", "bom", "won", "tap", "rub", "oil", "rem", "men", 
 "pom", "lou", "lav", "kid", "hun", "hol", "hel", "han", "nod", "nov", "gil", 
 "fum", "gib", "noc", "dou", "ald", "may", "gag", "doo", "vot", "old", "cry", 
 "fid", "coc", "taw", "rim", "doz", "ese", "spo", "nig", "lov", "wax", "bal", 
 "dac", "ens", "ash", "thu", "wak", "kle", "bap", "lex", "lei", "ile", "chy", 
 "mix", "jan", "ver", "spa", "ros", "sty", "pat", "mop", "min", "mim", "rou", 
 "jet", "jer", "wad", "mam", "hay", "hag", "gym", "gob", "gid", "eve", "div", 
 "dan", "cri", "ert", "nen", "ill", "pie", "lag", "bru", "bos", "eon", "bib", 
 "dos", "eer", "bes", "sot", "ciz", "had", "nac", "gol", "bum", "cet", "six", 
 "sed", "sar", "pan", "wed", "sei", "mid", "pau", "lob", "jam", "hin", "hid", 
 "het", "haz", "gua", "gig", "ule", "fer", "vad", "sod", "don", "lik", "wel", 
 "mun", "nad", "voy", "niv", "vas", "jun", "mie", "shy", "ade", "bli", "nev", 
 "hav", "she", "ban", "dad", "ath", "ier", "kha", "ray", "poc", "nul", "lyz", 
 "giz", "rit", "lel", "lah", "all", "deb", "gog", "anc", "sop", "dum", "dap", 
 "edg", "win", "wid", "veg", "the", "sen", "pol", "mur", "mis", "ond", "mea", 
 "lil", "lif", "kit", "kan", "jug", "jin", "jan", "ink", "hys", "hus", "hil", 
 "pad", "toe", "gim", "gab", "fol", "fad", "vap", "ene", "gyp", "gad", "dys", 
 "dur", "sua", "fam", "rah", "kar", "dai", "cun", "nim", "cof", "pea", "tau", 
 "buf", "hil", "lyn", "ell", "bla", "vex", "jew", "bub", "bay", "pip", "vow", 
 "lee", "ole", "ans", "one", "tig", "rak", "and", "ide", "lud", "kan", "gie", 
 "ach", "wet", "tan", "tai", "ste", "sew", "pen", "pal", "pag", "poi", "new", 
 "mus", "mug", "sog", "mes", "sag", "tyr", "lin", "lil", "lau", "ski", "kay", 
 "jit", "jen", "jel", "hit", "hex", "hen", "has", "hal", "gul", "gor", "ger", 
 "gem", "fos", "for", "far", "iar", "nox", "jac", "egg", "due", "own", "moc", 
 "jay", "cro", "ued", "sue", "ial", "too", "che", "cha", "lia", "rif", "lix", 
 "bev", "das", "rut", "daz", "tub", "yan", "zar", "awe", "ute", "ash", "pod", 
 "toc", "tos", "och", "fon", "leu", "gui", "gue", "gil", "noi", "lom", "van", 
 "val", "zip", "wis", "two", "tur", "tor", "tar", "tam", "sha", "sab", "rug", 
 "ruf", "rob", "wir", "pup", "pum", "pug", "pom", "peo", "wee", "odd", "quo", 
 "rib", "mas", "now", "lol", "liv", "len", "nur", "kel", "job", "jew", "jaw", 
 "jac", "luc", "uid", "muz", "hon", "hoe", "hug", "hep", "hec", "goo", "fro", 
 "fri", "voc", "tou", "eng", "roc", "ree", "dun", "dor", "cee", "mag", "neb", 
 "den", "cub", "coy", "vok", "vec", "gno", "web", "loc", "led", "pox", "scu", 
 "kov", "cag", "caf", "nag", "bow", "bos", "bor", "bol", "bog", "dhi", "cay", 
 "bak", "lau", "zel", "cue", "gur", "apt", "loo", "aph", "rhi", "arc", "ise", 
 "dre", "nia", "biv", "gic", "oth", "jar", "aes", "dop", "ace", "dab", "bey", 
 "yel", "woe", "who", "wav", "war", "ter", "tal", "syc", "sun", "spu", "slo", 
 "sin", "sib", "shi", "sca", "sam", "rus", "rud", "ran", "sce", "pra", "pla", 
 "pas", "raz", "lae", "muf", "may", "max", "mat", "map", "jor", "nil", "rai", 
 "mad", "lyr", "lug", "zie", "lib", "lan", "poo", "kib", "kel", "kar", "pok", 
 "joc", "jer", "jag", "jab", "sou", "imp", "hun", "hor", "hir", "hin", "hei", 
 "hay", "hai", "gre", "gra", "gol", "god", "fif", "dly", "fib", "bry", "ech", 
 "dix", "nah", "lir", "deb", "cre", "fut", "cle", "cin", "rop", "hua", "dee", 
 "ire", "peu", "vag", "yon", "buy", "bul", "bud", "bru", "tly", "bra", "bon", 
 "zet", "fry", "ett", "bea", "sho", "lla", "bab", "bab", "bai", "wry", "nue", 
 "aug", "ass", "peg", "ius", "anx", "pov", "nae", "ode", "mom", "nab", "ale", 
 "bam", "tae", "cla", "wob", "wes", "vol", "vir", "vic", "tru", "tri", "pog", 
 "tib", "tho", "swa", "sta", "sel", "sax", "sat", "rom", "sow", "ray", "raw", 
 "ram", "puz", "ets", "req", "lyg", "pix", "pim", "pau", "pap", "pam", "owl", 
 "ooz", "oat", "nix", "nib", "nel", "nar", "nan", "nop", "mol", "rul", "med", 
 "sly", "mai", "moi", "lon", "pud", "les", "zig", "lat", "rov", "ked", "jux", 
 "jot", "jog", "jib", "jes", "mai", "jad", "yar", "irk", "ept", "hus", "hub", 
 "itz", "how", "hov", "hou", "nob", "hes", "hei", "hea", "mow", "haw", "hai", 
 "gro", "ose", "rau", "gen", "gaz", "gap", "gan", "ins", "lup", "ful", "fru", 
 "zli", "fra", "fop", "flo", "fag", "ult", "hic", "err", "soi", "jah", "oed", 
 "dye", "dra", "doy", "dou", "dah", "dom", "dod", "siv", "enc", "ane", "nud", 
 "mob", "dem", "dal", "daf", "slo", "cyn", "few", "kli", "cox", "spy", "coo", 
 "rer", "com", "quy", "rho", "kee", "tah", "vix", "cau", "cap", "dav", "zan", 
 "kum", "bun", "jum", "bud", "roo", "nei", "bri", "sla", "sai", "gna", "gey", 
 "cie", "cac", "bie", "blu", "bil", "bez", "bev", "beg", "bop", "zoo", "tok", 
 "lai", "baf", "bac", "syr", "dea", "nid", "dix", "lyp", "toi", "noy", "nex", 
 "rae", "lio", "tai", "lur", "aim", "gio", "zam", "yip", "yes", "yem", "xen", 
 "wol", "wiz", "wat", "was", "voo", "ves", "unc", "ump", "tym", "tus", "tun", 
 "tug", "tre", "tra", "tom", "tod", "tim", "tha", "ten", "tel", "tas", "syr", 
 "swe", "sul", "sud", "son", "emn", "sob", "sis", "sid", "she", "ser", "sax", 
 "sav", "urn", "sas", "sap", "saf", "rod", "riv", "rho", "red", "ras", "raf", 
 "por", "pon", "piz", "piv", "nyl", "ceu", "peg", "peb", "paw", "pae", "oph", 
 "poe", "oaf", "nup", "nic", "nes", "nak", "mul", "zin", "rey", "roe", "tov", 
 "mne", "mit", "mex", "lod", "maz", "chu", "mah", "lyn", "waf", "lor", "liz", 
 "lip", "lew", "yer", "law", "las", "lub", "lal", "kir", "kin", "kim", "ryn", 
 "kam", "kal", "jut", "jus", "jun", "jul", "jon", "jok", "jim", "jim", "jem", 
 "jef", "jas", "ish", "mez", "ich", "ice", "hou", "shu", "kai", "hip", "him", 
 "hik", "hew", "hec", "wai", "hau", "hat", "sle", "gus", "wog", "goe", "und", 
 "tep", "gay", "gau", "gau", "gas", "fri", "fre", "sak", "mox", "zes", "feu", 
 "fed", "nir", "uer", "ast", "dym", "him", "elf", "een", "ear", "buk", "dyb", 
 "dur", "dug", "dub", "zly", "dol", "dis", "dir", "jon", "die", "rik", "dia", 
 "deu", "des", "ere", "der", "dec", "daw", "iel", "dae", "tyl", "cur", "kly", 
 "its", "cow", "vus", "cop", "coo", "tio", "loi", "fax", "cig", "cic", "pah", 
 "cem", "cel", "caw", "cat", "noo", "noe", "leb", "cai", "cae", "ock", "zil", 
 "wow", "rax", "bob", "mey", "bis", "bet", "bes", "nef", "lea", "fud", "bee", 
 "nik", "bau", "bas", "rio", "iff", "zal", "awk", "von", "oir", "aux", 
 "ch\[EAcute]", "ath", "ymp", "ith", "qu\[EAcute]", "ant", "rex", "kor", 
 "ase", "amp", "gae", "kim", "ail", "aid", "hoy", "gou", "ary", "bys", "zir", 
 "zag", "zap", "zan", "yob", "yet", "yeo", "yel", "yap", "yam", "yak", "wok", 
 "wis", "wie", "wan", "wam", "vul", "vla", "viv", "vis", "vin", "vil", "ual", 
 "ven", "vel", "ush", "tyn", "tup", "tos", "ton", "tol", "tip", "til", "thu", 
 "tex", "teu", "tes", "tem", "ted", "tao", "taf", "tae", "tad", "syl", "sut", 
 "sus", "sum", "sue", "stu", "sto", "dli", "spi", "roi", "soy", "sov", "sou", 
 "sol", "sof", "sod", "sla", "sir", "sil", "sig", "sey", "sep", "sac", "run", 
 "rue", "ron", "rol", "rog", "rev", "reu", "res", "rem", "reg", "bek", "zor", 
 "rab", "bec", "que", "qua", "pyr", "pyr", "pyg", "pun", "pse", "pry", "pru", 
 "pre", "pow", "pop", "pei", "pyl", "plu", "pin", "pil", "pik", "pho", "phi", 
 "pew", "pet", "rox", "pea", "pav", "pav", "pam", "vip", "our", "ost", "ome", 
 "ohm", "oft", "oeu", "bei", "oar", "oak", "oak", "nub", "nip", "nim", "kon", 
 "nie", "nep", "nep", "nem", "naz", "nav", "nas", "nai", "nai", "myr", "muu", 
 "cly", "mun", "mos", "moo", "yev", "moi", "mir", "ael", "mey", "mem", "mei", 
 "sli", "jua", "ria", "mao", "seh", "lef", "jes", "mae", "lyd", "lud", "low", 
 "vre", "lou", "lot", "lom", "lis", "uor", "mou", "lim", "lep", "lei", "ume", 
 "wen", "leb", "laz", "voi", "ynx", "lar", "lap", "lao", "lam", "lab", "kro", 
 "kr\[OAcute]", "kro", "kra", "kos", "kon", "kyu", "kit", "kis", "kip", 
 "kil", "kha", "kes", "ker", "kep", "keg", "kis", "kat", "kai", "jua", "jos", 
 "jor", "ann", "jen", "jay", "jas", "ith", "sos", "vei", "teg", "ios", "inn", 
 "nez", "dyl", "bex", "hym", "hum", "hul", "hud", "hub", "hop", "hoo", "eys", 
 "hof", "hit", "his", "hie", "hey", "hey", "itt", "hew", "heu", "hep", "hef", 
 "hee", "haw", "kie", "haj", "kuk", "gyr", "guz", "guy", "guy", "gun", "gui", 
 "tli", "vim", "gou", "gow", "gir", "gin", "gib", "get", "gam", "mau", "gai", 
 "gab", "fou", "fob", "fiz", "fin", "fez", "fey", "feb", "fau", "fat", "fan", 
 "fak", "urb", "ude", "alt", "eve", "eur", "eth", "ruc", "nui", "fod", "ein", 
 "fie", "dvo", "dup", "duf", "cek", "dub", "dru", "doo", "doe", 
 "c\[EAcute]e", "dil", "dib", "ghi", "dex", "dew", "uge", "deg", "foe", 
 "d\[EAcute]b", "day", "dau", "dag", "vak", "cys", "cyr", "cyp", "cym", 
 "cyl", "cyc", "cao", "cum", "cul", "cud", "cru", "cri", "cra", "ote", "coy", 
 "cou", "l\[EAcute]e", "nou", "cos", "umn", "ors", "erc", "coe", "clo", 
 "dio", "chu", "cey", "gup", "ois", "cey", "cer", "fug", "cec", "llo", "ids", 
 "puc", "lyx", "cai", "bye", "bry", "ain", "bre", "swa", "bot", "zoi", "vik", 
 "bof", "boe", "bim", "bhu", "bei", "bay", "tik", "mew", "bap", "kla", "bai", 
 "baa", "zov", "axe", "awn", "awl", "auc", "ask", "ark", "arc", "pex", "ape", 
 "zac", "nio", "tiq", "ang", "gry", "nem", "moe", "ons", "maz", "ryl", "oes", 
 "ghe", "yah", "cio", "aes", "add", "zug", "zuc", "zom", "zom", "zlo", "zin", 
 "bwe", "zim", "zie", "zhu", "zhi", "zep", "zen", "zef", "zed", "zed", "zeb", 
 "zar", "zap", "uck", "hof", "yup", "yuk", "yuc", "you", "yon", "yok", "yid", 
 "yid", "ygg", "yew", "yev", "yer", "yep", "yen", "yea", "yaw", "yan", "tze", 
 "yam", "yal", "kut", "yak", "weh", "yah", "xho", "xer", "xen", "xan", "wyo", 
 "wyc", "att", "wun", "wro", "wot", "woo", "won", "wol", "wiv", "wit", "wip", 
 "wim", "wim", "waw", "wig", "why", "who", "whi", "wey", "wen", "wel", "wei", 
 "web", "way", "wat", "was", "wap", "wai", "wah", "wag", "vor", "vom", "vod", 
 "vos", "tue", "vip", "vie", "vhf", "vhf", "zue", "l\[AAcute]s", "veb", 
 "vau", "vat", "vat", "vas", "var", "vam", "kyr", "duz", "ute", "usa", "urg", 
 "lys", "uhf", "ugh", "ufo", "biq", "twi", "tux", "kic", "tul", "tuc", "tub", 
 "tua", "tsu", "tsi", "tsi", "jil", "tro", "une", "toy", "tou", "paz", "kyo", 
 "tof", "tod", "tnt", "tin", "tif", "cyd", "phu", "tek", "tef", "tbi", "tay", 
 "taw", "tav", "tau", "h\[ADoubleDot]u", "tad", "tac", "tab", "szi", "ont", 
 "syd", "syb", "syb", "sut", "sui", "suf", "orn", "sri", "bok", "spo", "soz", 
 "yuz", "soy", "fl\[EAcute]", "sos", "sor", "som", "zhe", "r\[EAcute]e", 
 "gn\[EAcute]", "soc", "soc", "sna", "smo", "smo", "smi", "sme", "sky", 
 "sku", "ske", "sim", "sik", "ouk", "urd", "sie", "sic", "sib", "shy", "sho", 
 "loh", "shh", "sex", "sew", "sev", "seu", "sem", "juk", "ogy", "see", "seb", 
 "sea", "sco", "sci", "say", "sau", "tay", "sat", "hed", "yed", "yut", "sai", 
 "sag", "gac", "dhu", "sad", "sab", "saa", "ryu", "rye", "rut", "rum", "rud", 
 "roy", "rox", "rou", "wei", "rot", "roo", "rom", "yal", "rip", "rim", "ril", 
 "rig", "rie", "rib", "rhu", "boi", "rhi", "rhe", "kja", "rey", "rex", "vue", 
 "req", "dez", "ict", "ref", "rca", "oul", "ram", "raj", "rai", 
 "r\[ODoubleDot]k", "rag", "raf", "rae", "rad", "qum", "qui", "qed", "qad", 
 "pyx", "pyn", "pym", "pyg", "put", "pur", "puk", "puf", "pue", "puc", "pto", 
 "psy", "pso", "psi", "erb", "\[CCedilla]al", "g\[EAcute]e", "ect", "uct", 
 "pri", "pr\[EAcute]", "pra", "ppm", "poz", "pow", "pot", "p\[OHat]r", "poo", 
 "pey", "poe", "pod", "plo", "pli", "nha", "\[NTilde]on", "laf", "pif", 
 "pic", "zas", "pia", "pia", "ips", "phe", "phd", "aoh", "pha", "pep", "pem", 
 "pem", "pel", "koe", "pej", "pei", "pax", "paw", "ysm", "jom", "pai", "pah", 
 "rew", "pad", "pab", "pab", "blo", "oys", "owe", "vum", "tr\[EAcute]", 
 "oui", "oua", "ost", "osh", "ore", "ord", "orb", "opt", "oph", "ope", "ooh", 
 "yad", "olm", "gop", "kra", "oik", "ohi", "oer", "boe", "nye", "nuz", "num", 
 "nug", "nth", "noz", "kuz", "nov", "vem", "not", "nos", "mah", "nix", "nis", 
 "veh", "nia", "net", "neh", "neg", "nef", "ned", "neb", "nco", "nay", "nat", 
 "mib", "nam", "tls", "nag", "myx", "zak", "mut", "mum", "luk", "muk", "mrs", 
 "moz", "zam", "via", "moo", "gom", "mom", "lyb", "mog", "mne", "mix", "mit", 
 "nao", "mim", "wau", "mik", "mic", "cah", "met", "dek", "mei", "meg", "mec", 
 "guf", "mba", "mba", "zur", "maw", "mav", "zoh", "n\[EAcute]e", "als", 
 "sif", "gni", "ryk", "tsa", "duk", "mam", "mak", "maj", "maj", "bha", "dei", 
 "ame", "naw", "lyl", "lye", "lux", "lul", "lub", "lsd", "loz", "loy", "lox", 
 "lov", "fah", "gev", "lol", "loe", "llb", "lju", "ege", "lie", "lha", "lex", 
 "eme", "lev", "ler", "leo", "lem", "leh", "leg", "lee", "lea", "laz", "lay", 
 "lak", "sez", "lac", "kyu", "kyo", "kwa", "kur", "kuo", "kun", "kui", "kud", 
 "kru", "kow", "kow", "koh", "dak", "zia", "kip", "osk", "zim", "khz", "khu", 
 "key", "kew", "kev", "ket", "fuf", "kep", "yat", "kem", "kee", "kea", "tza", 
 "kay", "kau", "kul", "kap", "kao", "myk", "kaf", "kaa", "jut", "jug", "jud", 
 "joy", "jos", "sef", "jop", "jol", "jog", "joe", "joc", "job", "joa", "jiv", 
 "jin", "jif", "jid", "jez", "vah", "jax", "jav", "jar", "jap", "jap", "jal", 
 "jai", "uar", "jag", "iah", "ire", "raq", "ips", "iph", "iou", "ity", "imf", 
 "bue", "i'm", "ilk", "ikh", "ike", "i'd", "amb", "bia", "gea", "zah", "huz", 
 "huy", "hux", "hut", "huh", "hug", "hue", "hud", "hnm", "yhn", "hot", "hok", 
 "kam", "zol", "hod", "h'm", "hiv", "yas", "hez", "het", "hem", "heg", "heb", 
 "haz", "hau", "has", "kah", "nuk", "hak", "jis", "hag", "haf", "had", "gyv", 
 "gyp", "gyn", "gwa", "guv", "gur", "gul", "guj", "zot", "gug", "faw", "guf", 
 "gue", "gru", "gr\[UDoubleDot]", "gri", "gos", "gop", "gon", "gom", "wyn", 
 "goi", "goi", "gnu", "gnp", "gmt", "glo", "gla", "giu", "gio", "gud", "gid", 
 "gia", "gha", "gaw", "gew", "tys", "gem", "gei", "gei", "geh", "gay", "gav", 
 "gav", "eed", "\[CCedilla]on", "ete", "gaf", "gae", "fun", "fug", "fry", 
 "fro", "foy", "fox", "fow", "fou", "fos", "fei", "foo", "fon", "fol", "fok", 
 "foi", "fli", "fiv", "fil", "fez", "tuc", "fel", "faz", "fay", "fay", "oms", 
 "fal", "kir", "fai", "faf", "unt", "ewe", "ryd", "erg", "quu", "eph", "asm", 
 "emu", "elv", "lul", "elm", "ott", "elk", "eld", "eke", "eis", "eir", "ein", 
 "eif", "ehr", "eff", "eel", "ebb", "dyl", "r\[AAcute]k", "dvi", "dus", 
 "d\[UDoubleDot]s", "dul", "duf", "dud", "dud", "dry", "ads", "dow", "dov", 
 "dot", "dos", "dop", "doi", "doe", "dob", "doa", "dne", "dna", "dmi", "dji", 
 "ghy", "dik", "did", "dic", "dia", "dho", "dev", "deu", "\[EGrave]re", 
 "ims", "dei", "dee", "ddt", "daw", "dav", "vao", "dau", "jee", "ube", "dam", 
 "dai", "dag", "cza", "cyn", "cyg", "cyg", "cyc", "cyb", "cuz", "cus", "lew", 
 "cui", "soe", "ats", "cpu", "coz", "cox", "cov", "cot", "pax", 
 "t\[EGrave]g", "zio", "kry", "viz", "cok", "cog", "coc", "coa", "cyx", 
 "cni", "cly", "cli", "cla", "cir", "cid", "cic", "cia", "cho", "zee", "ubs", 
 "ops", "vez", "ch\[AHat]", "ryb", "tey", "cen", "cei", "ced", "cbs", "cay", 
 "cax", "cav", "tul", "pek", "ais", "cak", "cag", "cae", "cad", "byz", "byb", 
 "buz", "bux", "bux", "but", "uel", "buf", "dha", "buc", "zos", "boy", "bov", 
 "lez", "bou", "bom", "boi", "boc", "boc", "bla", "biz", "ack", "bir", "bik", 
 "jou", "bid", "bia", "bho", "beu", "gha", "beh", "beg", "bed", "bec", "bea", 
 "bbc", "bax", "bau", "bat", "t\[OAcute]k", "rom", "zai", "jul", "kok", 
 "bam", "bak", "kal", "bah", "ha'", "bah", "baf", "bae", "yur", "ayr", "aye", 
 "vun", "zeb", "auk", "att", "oll", "isk", "asp", "naz", "arn", "arm", "ark", 
 "are", "aph", "ang", "obe", "mok", "ind", "yce", "alp", "all", "eut", "alb", 
 "kad", "akh", "jax", "mee", "aft", "ael", "adz", "ams", "ach", "sae", 
 "b\[EAcute]s"}
